.envrc, .github/CODEOWNERS, .github/workflows/main.yml, .gitignore, .tool-versions, GNUmakefile, README.md, harness/api/application_test.go, harness/api/azure_cloudprovider_test.go, harness/api/encrypted_text_test.go, harness/api/service_test.go, harness/api/ssh_credential_test.go, harness/api/winrm_credential_test.go, utils/build.sh
This is my first PR into the repo to get used to the code base. I've added a GitHub Actions Workflow and tested it using my fork: https://github.com/vyas-n/harness-go-sdk/pull/1
=> Format Files + add golangci-lint

harness/cd/cac_service_test.go, harness/cd/client.go, harness/cd/client_test.go, harness/cd/errors.go, harness/helpers/envvars.go, harness/utils/http.go, logging/logging.go, logging/transport.go, session.go
Fixed an issue where you could only set authentication credentials through environment variables. https://github.com/harness-io/terraform-provider-harness/issues/71
=> Fixed auth configuration issue

.tool-versions, go.mod, go.sum, harness/cd/client.go, harness/cd/client_test.go, harness/cd/delegate_test.go, harness/cd/encrypted_text_test.go, harness/cd/secret_manager.go, harness/helpers/envvars.go, harness/nextgen/client.go, harness/nextgen/configuration.go, tools/go.mod, tools/go.sum, tools/tools.go
- Upgrade to golang 1.17
- Refactored CD and NG clients
- Fixed tests
=> Golang 1.17

go.mod, go.sum, harness/nextgen/api_pipelines.go, harness/nextgen/client.go, harness/nextgen/enum_environment_types.go, harness/nextgen/model_connector_response.go, harness/nextgen/model_entity_git_details.go, harness/nextgen/model_entity_git_details_helper.go, harness/nextgen/model_entity_git_details_options.go, harness/nextgen/model_entity_git_details_test.go, harness/nextgen/model_environment_response.go, harness/nextgen/model_pipeline.go, harness/nextgen/model_pipeline_yaml.go, harness/nextgen/model_pms_pipeline_response.go, harness/nextgen/model_pms_pipeline_response_serializer.go, harness/nextgen/model_service_response.go
**Nextgen**
- Added tweaks to environments
- Setup helpers for standardizing gitsync configs
- Better error handling and serialization for pipelines
=> [NG] Environment and Gitsync setup

harness/cd/cac.go, harness/cd/cac/types.go, harness/cd/cac/utils.go, harness/cd/cac_cloudprovider.go, harness/cd/cac_cloudprovider_test.go, harness/cd/cac_test.go
Solves https://github.com/harness/terraform-provider-harness/issues/59
=> Implement new cac delete method

harness/nextgen/api_secrets_test.go, harness/nextgen/client_test.go, harness/nextgen/client_utils.go, harness/nextgen/configuration.go, harness/nextgen/enum_secret_spec_types.go, harness/nextgen/enum_secret_text_value_types.go, harness/nextgen/enum_secret_types.go, harness/nextgen/model_secret.go, harness/nextgen/model_secret_serializer.go, harness/nextgen/model_secret_text_spec.go
=> Fix serialization of secret entities

go.mod, go.sum, harness/cd/application.go, harness/cd/application_test.go, harness/cd/client.go, harness/cd/graphql/enum_tag_entity_types.go, harness/cd/graphql/model_attach_tag_input.go, harness/cd/graphql/model_attach_tag_payload.go, harness/cd/graphql/model_create_application_input.go, harness/cd/graphql/model_detach_tag_input.go, harness/cd/graphql/model_tag_link.go, harness/cd/graphql/types.go, harness/cd/tags.go, harness/cd/tags_test.go
This gives the ability to attach and detach tags to various resources.
=> Implemented AttachTag and DetachTag functionality

harness/nextgen/api_secrets.go
Models and enum changes for secret file type
=> [PL-25839]: Models and enum changes for secret file type

harness/nextgen/enum_ssh_authentication_type.go, harness/nextgen/enum_ssh_config_type.go, harness/nextgen/enum_ssh_specification_type.go, harness/nextgen/enum_tgt_generation_method_type.go, harness/nextgen/model_base_ssh_spec.go, harness/nextgen/model_kerberos_config.go, harness/nextgen/model_kerberos_config_spec_serialization.go, harness/nextgen/model_secret_serializer.go, harness/nextgen/model_ssh_auth.go, harness/nextgen/model_ssh_auth_serializer.go, harness/nextgen/model_ssh_config.go, harness/nextgen/model_ssh_config_serialization.go, harness/nextgen/model_ssh_credential_spec.go, harness/nextgen/model_ssh_key_spec.go, harness/nextgen/model_ssh_specification_serializer.go, harness/nextgen/model_tgt_generation_spec_dto.go, harness/nextgen/model_tgt_generation_spec_serializer.go
Model and enum changes for sshkey type secret
=> [PL-25840]: Model and enum changes for sshkey type secret

harness/nextgen/model_attribute_filter.go, harness/nextgen/model_resource_selector_v2.go
=> Added attribute filter model

harness/nextgen/api_environment_extensions.go, harness/nextgen/api_environment_test.go, harness/nextgen/api_organization_extensions.go, harness/nextgen/api_organization_test.go, harness/nextgen/api_project_extensions.go, harness/nextgen/api_project_test.go, harness/nextgen/api_services_extensions.go, harness/nextgen/api_services_test.go, harness/nextgen/api_user_group_extensions.go, harness/nextgen/api_user_group_test.go
Return HTTP status code from all APIs
=> fix: [PL-27862]: Return HTTP status code from all APIs

harness/nextgen/client.go
-  fixing client for environemntGroup
=> [SPG-203]: fixing client for environemntGroup

harness/nextgen/docs/ServiceRequest.md, harness/nextgen/docs/ServiceResponse.md, harness/nextgen/docs/ServiceResponseDetails.md, harness/nextgen/docs/ServicesApi.md, harness/nextgen/model_service_request.go, harness/nextgen/model_service_response_details.go
=> [SPG-219]: adding service API files.

harness/nextgen/api_clusters.go, harness/nextgen/docs/ClustersApi.md
=> [CDS-43546]: adding cluster API

harness/cd/execution.go, harness/cd/execution_test.go, harness/cd/graphql/enum_deployment_tag_types.go, harness/cd/graphql/enum_export_executions_status_types.go, harness/cd/graphql/enum_number_operators.go, harness/cd/graphql/enum_time_operators.go, harness/cd/graphql/model_deployment_tag_filter.go, harness/cd/graphql/model_execution_filter.go, harness/cd/graphql/model_export_executions_input.go, harness/cd/graphql/model_export_executions_payload.go, harness/cd/graphql/model_number_filter.go, harness/cd/graphql/model_time_filter.go
**1. Feature description**
This feature provides support for ExportExecutions graphql api.
https://docs.harness.io/article/pe7vgjs6sv-export-deployment-logs
=> feat: [CDS-43281]: Adding ExportExecutions support

harness/nextgen/client.go
=> [SPG-522]: adding infra TF

harness/nextgen/enum_infrastructure_deployment_types.go, harness/nextgen/enum_infrastructure_types.go
- updating enums in infra
<details>
=> [SPG-731]: updating infra doc

harness/nextgen/model_connector_info.go, harness/nextgen/model_connector_info_serializer.go
=> Changes to add azure cloud cost connector

harness/nextgen/model_connector_info.go, harness/nextgen/model_connector_info_serializer.go
=> Add azure key vault connector type

harness/nextgen/docs/EmailConfigDto.md, harness/nextgen/model_email_config_dto.go, harness/nextgen/model_notification_setting_config_dto.go
=> SPG-495: Add SendEmailToAllUsers

harness/cd/graphql/types.go, harness/cd/triggers.go
=> Update trigger in cg

harness/cd/execution.go, harness/cd/execution_test.go, harness/cd/executions/types.go, harness/cd/executions/utils.go, harness/cd/executions/utils_test.go, harness/helpers/httphelpers.go
=> feat: [CDS-43019]: abort and cancel pipeline/workflow

harness/nextgen/model_spot_connector.go
=> [feat]: [CDS-45294]: Fix Boolean field for Spot connector

harness/cd/client.go, harness/helpers/envvars.go, harness/nextgen/configuration.go, logging/transport.go
=> SPG-435: Mask API Key in http request logs

harness/nextgen/api_filter.go
-  adding TF resource for template
<details>
=> SPG-823 adding TF resource for template

harness/cd/cac/enums.go, harness/cd/cac/types.go
https://harness.atlassian.net/browse/CDS-46959
<details>
=> Added version and changed variable type for custom deployment

logging/transport.go
=> SPG-435: Fix APIKey Masking

harness/nextgen/model_connector_info.go, harness/nextgen/model_jenkins_authentication.go, harness/nextgen/model_jenkins_authentication_spec_serialization.go
=> Add jenkins authentication serializer

harness/helpers/testhelpers.go
=> Add vault root token secret enum

harness/nextgen/enum_connector_types.go
=> Update connector types enum to include jenkins type

harness/nextgen/api_user.go, harness/nextgen/docs/AddUsersDto.md, harness/nextgen/docs/UserApi.md, harness/nextgen/model_add_users_dto.go, harness/nextgen/model_add_users_response.go, harness/nextgen/model_email_config_dto.go, harness/nextgen/model_response_dto_add_users_response.go
- adding user TF resource
<details>
=> SPG-443 adding user TF resource

harness/nextgen/model_connector_info_serializer.go
=> Update connector info serializer

harness/nextgen/model_jenkins_authentication_spec_serialization.go
=> Update jenkin authentication serializer

harness/nextgen/model_jenkins_authentication_spec_serialization.go
=> Update jenkins auth serializer

harness/nextgen/README.md, harness/nextgen/api_slo.go, harness/nextgen/docs/SloApi.md
Add terraform support for the MS & SLO CRUD APIs. Changes in APIs path as per convention.
<details>
=> feat: [SRM-13159]: Add teraform support for the MS & SLO CRUD APIs. Changes in APIs path as per convention.

harness/nextgen/api_environment_group.go, harness/nextgen/api_environments.go, harness/nextgen/api_services.go
=> feat: [cds-48983]: have added force delete query param

harness/nextgen/docs/Servicev1Cluster.md, harness/nextgen/model_servicev1_cluster.go
=> feat: [CDS-46620]: Added Tags in Servicev1cluster for GitOps

harness/nextgen/docs/ClustersClusterCreateRequest.md, harness/nextgen/docs/ClustersClusterUpdateRequest.md, harness/nextgen/model_clusters_cluster_create_request.go, harness/nextgen/model_clusters_cluster_update_request.go
=> feat: [CDS-46620]: Tags added to Create and Update Req Body for GitOps Cluster

harness/nextgen/model_add_users_dto.go
- Updated the AddUserDto Struct , as for no role binding provided it would omit that , due to which API responded 500
<details>
=> Fixed AddUserDto Struct

logging/transport.go
Masking of API Key Fixed
<details>
=> Fixed Masking of API Key In Debug Console

harness/nextgen/api_environments.go
Update Service Overrides Get/Delete APIs
<details>
=> [CDS-57664]: Update api_environments.go

harness/nextgen/docs/TasConnector.md, harness/nextgen/docs/TasCredential.md, harness/nextgen/docs/TasCredentialSpec.md, harness/nextgen/docs/TasManualDetails.md, harness/nextgen/enum_connector_types.go, harness/nextgen/enum_infrastructure_types.go, harness/nextgen/enum_tas_credential_types.go, harness/nextgen/model_connector_info.go, harness/nextgen/model_connector_info_serializer.go, harness/nextgen/model_tas_connector.go, harness/nextgen/model_tas_credential.go, harness/nextgen/model_tas_credential_serializer.go, harness/nextgen/model_tas_credential_spec.go, harness/nextgen/model_tas_manual_details.go
Changes:
- Added support for TAS connector and infrastructure
- Added support for quarterly freeze
<details>
=> feat: [CDS-56975]: Suppport for TAS and quarterly freeze

harness/nextgen/model_app_dynamics_health_source_spec.go, harness/nextgen/model_aws_prometheus_health_source_spec.go, harness/nextgen/model_cloud_watch_metrics_health_source_spec.go, harness/nextgen/model_custom_health_source_metric_spec.go, harness/nextgen/model_datadog_log_health_source_query_dto.go, harness/nextgen/model_datadog_log_health_source_spec.go, harness/nextgen/model_datadog_metric_health_source_spec.go, harness/nextgen/model_dynatrace_health_source_spec.go, harness/nextgen/model_elk_health_source_query_dto.go, harness/nextgen/model_elk_health_source_spec.go, harness/nextgen/model_error_tracking_health_source_spec.go, harness/nextgen/model_new_relic_health_source_spec.go, harness/nextgen/model_prometheus_health_source_spec.go, harness/nextgen/model_splunk_health_source_query_dto.go, harness/nextgen/model_splunk_health_source_spec.go, harness/nextgen/model_splunk_metric_health_source_spec.go, harness/nextgen/model_stackdriver_log_health_source_query_dto.go, harness/nextgen/model_stackdriver_log_health_source_spec.go, harness/nextgen/model_stackdriver_metric_health_source_spec.go
=> [fix]: [SRM-14684]: changing the query class to remove conflict.

harness/nextgen/client.go
Reverts harness/harness-go-sdk#336
=> Revert "fix:[PL-39286]: fixed URL Encoding for characters with space"

docs/JiraPatPassword.md, harness/nextgen/enum_jira_auth_types.go, harness/nextgen/model_jira_authentication_serializer.go, harness/nextgen/model_jira_pat_password.go
=> feat:[CDS-57089]: added Jira Pat auth type

harness/nextgen/docs/EnvironmentGroupResponse.md, harness/nextgen/model_environment_group_response.go
Addition of yaml field to env. group response
<details>
=> [feat]: [CDS-69600]: Addition of yaml field to env. group response

harness/nextgen/model_access_point_meta.go
Update the load balancer model
<details>
=> Update the load balancer model

harness/nextgen/enum_infrastructure_types.go
=> feat: [CDS-57635]: add AWS SAM infrastructure type

harness/nextgen/README.md, harness/nextgen/api_service_overrides.go, harness/nextgen/docs/ServiceOverridesApi.md
=> [fix]: [CDS-72208]: Overrides V2 Api Get Call Modification

harness/nextgen/api_agents.go, harness/nextgen/docs/AgentsApi.md
=> feat: [CDS-70803]: GitOps at Org level

harness/nextgen/model_monitored_service_dto.go
=> [fix]: [SRM-15255]: Removing enabled scope from terraform.

harness/nextgen/model_docker_connector.go
=> [CDS-75383]: adding executeondelegate field for docker connector

harness/nextgen/model_docker_connector.go
=> [CDS-75383]: removing omit empty field

harness/nextgen/api_environment_group.go, harness/nextgen/docs/EnvironmentGroupApi.md
=> [feat]: [CDS-77080]: Make org and project identifier optional for env group

harness/cd/cac.go, harness/cd/cac/types.go, harness/cd/cac/utils.go, harness/cd/cac_service.go
Parsing the entityYaml response so we dont need to transverse the directory tree.
<details>
=> feat: [CDS-77798]: adding entity yaml in the response

harness/nextgen/enum_github_http_credential_types.go, harness/nextgen/model_github_http_credentials.go, harness/nextgen/model_github_http_credentials_serializer.go
=> CI-9639: Added GithubApp in Http credentials of Github Connector

harness/cd/cac.go, harness/cd/cac/types.go, harness/cd/cac/utils.go, harness/cd/cac_service.go
This reverts commit e61a7891add308f7e7fc2ae79544c0cc756fbb87, reversing changes made to 822768ecb2b9563c27319f3f2aac4632662fb0f6.
<details>
=> Revert "Merge pull request #396 from harness/cds-77798"

harness/nextgen/api_connectors.go, harness/nextgen/api_connectors_test.go
Add force delete option for connectors API
<details>
=> fix: [CDS-82953]: Add force delete option for connectors

harness/nextgen/api_cloud_cost_auto_stopping_fixed_schedules.go
This was missed the original release
=> fix : [CCM-14434] API key based authentication for fixed schedule

harness/nextgen/enum_metric_threshold_types.go, harness/nextgen/model_metric_threshold.go, harness/nextgen/model_metric_threshold_serializer.go
=> [fix]: [SRM-16226]: added the spec in the metric threshold

.github/pull_request_template.md
=> fix: [BT-6060]: Update pull_request_template.md

harness/nextgen/docs/AwsCredential.md, harness/nextgen/model_aws_credential.go
Added support for aws region field in aws connector.
<details>
=> [fix]: [CDS-85006]: Add region field to aws connector

harness/nextgen/model_gcp_connector.go
=> [PL-38915]:Added Support for execute on Delegate in GCP Connector

harness/nextgen/api_agents.go
=> fix: [CDS-83545]: fix fetching deployment yaml

harness/nextgen/api_agents.go
=> fix: [CDS-83545]: fix agent update

harness/nextgen/model_metric_less_service_level_indicator_spec.go, harness/nextgen/model_request_based_service_level_indicator_spec.go, harness/nextgen/model_window_based_service_level_indicator_spec.go
=> fix: [SRM-16344]: Add SLO DTO changes.

harness/nextgen/enum_sli_evaluation_type.go, harness/nextgen/model_composite_service_level_objective_spec.go, harness/nextgen/model_service_level_indicator_dto.go, harness/nextgen/model_simple_service_level_objective_spec.go, harness/nextgen/model_window_based_service_level_indicator_spec.go
=> fix: [SRM-16344]: Update SLO DTOs.

harness/nextgen/api_monitored_service.go
Parse error message for 400 & 500 status code for monitored service
<details>
=> feat: [SRM-16369]: read response message for 400 & 500 code for monitored service

harness/nextgen/api_slo.go
Parse error message for 400 & 500 status code for slo
<details>
=> fix: [SRM-16391]: read response message for 400 & 500 code for slo.

harness/nextgen/api_project.go, harness/nextgen/enum_error_codes.go
This PR adds error handling for EntityNotFoundException 
<details>
=> feat:[PL-43643]: Added error handling for EntityNotFoundException

harness/nextgen/api_feature_flags.go
Add optional force delete option to the feature flag delete endpoint
<details>
=> feat: [FFM-10628]: Add force delete option for feature flags

harness/nextgen/api_feature_flags.go
Add flag PUT endpoint to generated feature flags api spec
<details>
=> feat: [FFM-10748]: Add flag PUT endpoint

harness/nextgen/model_custom_secret_manager.go
Update the Timeout type from int64 to int for Custom Secret Manager
<details>
=> fix: [PL-48388]: Update custom secret manager timeout type

harness/nextgen/enum_secret_text_value_types.go
Add Secret Value type for Custom Secret Manager. 
<details>
=> feat: [PL-49333]: Support Secret for Custom Secret Manager

harness/nextgen/enum_gcp_auth_types.go, harness/nextgen/model_gcp_connector_credential_serializer.go, harness/nextgen/model_gcp_oidc_details.go
Adding GCP OIDC auth in go SDK
changes similar to AWS OIDC: https://github.com/harness/harness-go-sdk/pull/492
<details>
=> feat: [CDS-84984]: adding oidc auth in gcp connector

harness/nextgen/enum_gcp_auth_types.go
Adds oidc authentication as a valid GCP connector authentication type.
<details>
=> feat: Add oidc authentication as valid auth type

harness/nextgen/api_applications.go, harness/nextgen/docs/ApplicationsApi.md, harness/nextgen/model_servicev1_application.go
=> feat: [CDS-98275]: Add skipRepoValidation for gitops application

harness/nextgen/enum_change_source_types.go, harness/nextgen/model_change_source_dto.go, harness/nextgen/model_change_source_dto_serializer.go, harness/nextgen/model_custom_deploy_change_source_spec.go, harness/nextgen/model_custom_ff_change_source_spec.go, harness/nextgen/model_custom_incident_change_source_spec.go
Add support for CustomIncident, CustomDeploy and CustomFF
<details>
=> fix: [CHAOS-6159]: Add support for custom change sources.

harness/nextgen/api_project_mappings.go
rename identifier sent in request
<details>
=> fix: [CDS-99254]: Fix gitops mapping v2 api.

harness/nextgen/README.md, harness/nextgen/api_user_group.go, harness/nextgen/docs/UserGroupApi.md
Added new API in Go SDK with path `/ng/api/v2/user-groups/{identifier}` to get a user group with user emails
<details>
=> feat: [PL-55889]: Added new API in Go SDK

harness/nextgen/api_repository_credentials.go
Terraform provider should recreate repo cred if deleted but exists in terraform state
<details>
=> fix: [CDS-101073]: Fix repo cred resource recreate in TF.

harness/nextgen/api_applications.go, harness/nextgen/api_repositories.go, harness/nextgen/docs/ApplicationsApi.md, harness/nextgen/docs/RepositoriesApi.md, harness/nextgen/model_servicev1_application.go
Added support for MultiSource applications.
Also added force delete repository flag.
<details>
=> feat: [CDS-98794]: Add support for multi-source apps in GitOps.

harness/nextgen/enum_ccm_features.go
=> feat:[CCM-20085]: Add Governance as feature in CCM Connector Features

harness/nextgen/api_agents.go, harness/nextgen/docs/AgentsApi.md
=> feat: [CDS-104468]: add withCredentials option to gitops agent get api

harness/nextgen/model_pipeline_filter_properties.go
=> feat: [PIPE-24072]: Added the pipeline name

harness/nextgen/model_gitlab_connector.go
=> fix:[IMPENG-324]: updated the GitlabConn Struct using the latest swagger

harness/nextgen/api_agents.go, harness/nextgen/docs/AgentsApi.md, harness/nextgen/model_v1_agent_yaml_query.go
=> feat: [CDS-102304]: Add private key param for fetching deployment yaml.

harness/nextgen/model_gitlab_connector.go
=> fix: [IMPENG-324]: Type_ fix for gitlab conn.

harness/nextgen/docs/JdbcServiceAccountDto.md, harness/nextgen/enum_jdbc_auth_types.go, harness/nextgen/model_jdbc_authentication_serializer.go, harness/nextgen/model_jdbc_connector.go, harness/nextgen/model_jdbc_service_account_dto.go
Adding new auth type ServiceAccount for JDBC connector
<details>
=> [feat]: [DBOPS-845]: Support for ServiceAccountToken JDBC connector

harness/nextgen/client.go, harness/nextgen/iacm_model_create_workspace_request_body.go, harness/nextgen/iacm_model_show_workspace_response_body.go, harness/nextgen/iacm_model_update_workspace_request_body.go
adjust iac workspace API client to support varsets
<details>
=> feat: [IAC-2926]: adjust iac workspace API to support varsets

harness/nextgen/api_feature_flags.go
Add api call for restoring an archived flag
<details>
=> fix: [FFM-12248]: add restore feature flag api call

harness/har/docs/OneOfRegistryConfig.md, harness/har/docs/OneOfUpstreamConfigAuth.md, harness/har/docs/RegistryConfig.md, harness/har/model_one_of_upstream_config_auth.go, harness/har/model_registry_config.go, harness/har/model_upstream_config.go
Updated Model for Upstream Support
<details>
=> feat: [AH-915]: Updated Model for Upstream Support

harness/nextgen/enum_file_usage.go
Update FILE Usage Enum
```go
ManifestFile: "MANIFEST_FILE",
Config:       "CONFIG",
Script:       "SCRIPT",
```
<details>
=> fix: [CDS-106931] Update FILE Usage Enum

harness/cd/unpublished/types.go, harness/nextgen/docs/VaultConnector.md, harness/nextgen/model_vault_connector.go
=> feat: [PL-58649]: Added JWT auth config in VaultConnector

harness/nextgen/model_terraform_cloud_connector.go
Added missing execute on delegate field to Terraform Cloud Connector model
<details>
=> fix:[CDS-107597] Added missing execute on delegate field

harness/nextgen/api_input_sets.go, harness/nextgen/api_pipelines.go
=> feat: [CDS-107148]: Update query params for edit git details

harness/nextgen/model_environment_response_details.go, harness/nextgen/model_infrastructure_response_dto.go, harness/nextgen/model_service_overrides_response_dtov2.go, harness/nextgen/model_service_response_details.go
=> feat: [CDS-107148]: Add connector ref to get service response

harness/nextgen/enum_azure_repo_api_auth_types.go, harness/nextgen/enum_azure_repo_connection_types.go, harness/nextgen/enum_azure_repo_http_credential_types.go, harness/nextgen/enum_connector_types.go, harness/nextgen/model_azure_repo_api_access.go, harness/nextgen/model_azure_repo_api_access_serializer.go, harness/nextgen/model_azure_repo_authentication.go, harness/nextgen/model_azure_repo_authentication_serializer.go, harness/nextgen/model_azure_repo_config.go, harness/nextgen/model_azure_repo_http_credentials.go, harness/nextgen/model_azure_repo_http_credentials_serializer.go, harness/nextgen/model_connector_info.go, harness/nextgen/model_connector_info_serializer.go
=> [feat]: [CDS-109317]: Azure Repo Connector changes

harness/nextgen/model_connector_info_serializer.go
- Required to fetch **Harness Built-in Secret Manager** using API.
<details>
=> feat: [CDS-109831] Add parse for GcpKms connector type

harness/nextgen/iacm_model_create_workspace_request_body.go, harness/nextgen/iacm_model_show_workspace_response_body.go, harness/nextgen/iacm_model_update_workspace_request_body.go
support multiple connectors for IACM workspace
<details>
=> feat: [IAC-3539]: support multiple connectors for workspace

harness/nextgen/api_dashboards.go, harness/nextgen/api_dashboards_filter.go, harness/nextgen/api_dashboards_folder.go, harness/nextgen/docs/UpdateDashboardResponseResource.md, harness/nextgen/model_update_dashboard_response_resource.go
- Added support for x-api-key headers for each Dashboard and Folder function
- Fixed type from int to string for dashboard update dashboard_id field.
<details>
=> fix: [PL-48875]: CDB - Request header and model type updates

harness/nextgen/iacm_model_create_workspace_request_body.go, harness/nextgen/iacm_model_show_workspace_response_body.go, harness/nextgen/iacm_model_update_workspace_request_body.go
updates iac workspace response / requests
<details>
=> feat: [IAC-4116]: update workspaces

harness/chaos/api_security_governance_condition.go, harness/chaos/api_security_governance_rule.go, harness/chaos/client.go, harness/chaos/examples/security_governance/condition_example/main.go, harness/chaos/examples/security_governance/rule_example/main.go
feat: [CHAOS-8830]: Add support for chaos security governance
- Support for security governance's conditions CRUD
- Support for security governance's rules CRUD
<details>
[CHAOS-8830]: https://harness.atlassian.net/browse/CHAOS-8830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [CHAOS-8830]: Add support for chaos security governance
