harness/harness-go-sdk

harness/api/client.go
harness/api/consts.go
harness/cd/cac.go
harness/cd/encrypted_text.go
harness/cd/graphql.go
harness/cd/graphql_test.go
harness/cd/secret_manager.go
harness/cd/ssh_credential.go
harness/cd/version.go
harness/cd/winrm_credential.go
harness/utils/const.go

Fixes #64. Updates the endpoint configuration to account for the fully qualified path. So you can now set the endpoint to `https://app.harness.io/gateway/api` or `https://customer.com/api`.

Update the endpoint to the fully qualified api path

---

harness/cd/graphql/types.go

This is to add the irsa option to aws cloud provider in the graphql package so that it can be more up to date with the api.

adding irsa credentials options to aws cloud provider

---

harness/cd/approval.go
harness/cd/approval_test.go
harness/cd/client.go
harness/cd/graphql/enum_approval_action_types.go
harness/cd/graphql/model_approve_or_reject_approvals_input.go
harness/cd/graphql/types.go

This PR adds the [Approvals API](https://docs.harness.io/article/n43s95h2aj-use-approvals-api) to the SDK for CG.  
This implements the `approvalDetails` query and the `approveOrRejectApprovals` mutation

Add approvals for CG to SDK

---

harness/cd/approval.go
harness/cd/graphql/types.go

This fixes the output of approveOrRejectApprovals, which isn't being unmarshalled correctly.

Fix approveOrRejectApprovals output

---

harness/cd/graphql/types.go

This is just to fix the json tag for the AwsCloudProvider type in the graphql package.

fixing json tag for AwsCloudProvider type

---

harness/nextgen/api_secrets.go

The terraform provider resource secret file doesn't work.
The root cause has been identified here https://harness.atlassian.net/browse/PL-31762 
Due to the duplicate key 'file' put in the multi-part payload, the actual file content stored in harness SM is a string of the path to file instead of the actual file content.
With @rijajoo , we have regenerated the api client code. Using the most recent ng manager api generated client code, the payload looks like below, which still doesn't work. The payload doesn't even contain file data, which is even worse then before.
So instead of re-gen file, we will just do one line fix.
```2023-03-10 18:56:21 [DEBUG] harness-go-sdk harness-go-sdk API Request Details:
---[ REQUEST ]---------------------------------------
POST …
```

fix: [PL-31762]: additional key 'file' that causes manager to not read file content

---

harness/nextgen/client.go

This is happening because while encoding the spaces it is being sent wrong
Current Behaviour → searchTerm = ABC Project  , Query Goes as → ABC+Project
Expected Behaviour → ABC%20Project
This PR fixes the issues
<details>

fix:[PL-39286]: fixed URL Encoding for characters with space

---

harness/nextgen/docs/RancherConnector.md
harness/nextgen/model_rancher_connector.go

This change removes an unused field from rancher connector, just for cleanup. It isn't causing any failures in TF provider, since we ignore unknown fields while parsing connectors in Harness.
<details>

Remove unused field from rancher connector

---

harness/policymgmt/model_update_request_body2.go

- Due to presence of `omitEmpty` the policymgmt client was was setting the boolean field value to `null` instead of it's actual value to `false. Removing this field let's the marshaller send the field as `false`. 
<details>

fix: [CDS-76702]: Remove omitempty

---

harness/nextgen/api_delegate_token_resource.go

For get call of delegateTokens, delegateToken name is missing in the api. This is necessary to fetch a specific token as opposed to fetching all the tokens in the given scope.
<details>

fix: [PL-39175]: Added delegateToken name as a paramter when fetching delegate tokens

---

harness/nextgen/api_clusters.go
harness/nextgen/docs/ClusterBasicDto.md
harness/nextgen/docs/ClusterBatchRequest.md
harness/nextgen/docs/ClusterBatchResponse.md
harness/nextgen/docs/ClusterRequest.md
harness/nextgen/docs/ClusterResponse.md
harness/nextgen/docs/ClustersApi.md
harness/nextgen/model_cluster_basic_dto.go
harness/nextgen/model_cluster_batch_request.go
harness/nextgen/model_cluster_batch_response.go
harness/nextgen/model_cluster_request.go
harness/nextgen/model_cluster_response.go

These models and api's had to be regenerated since agentIdentifier is added to gitops clusters mapped to envs
<details>

fix: [CDS-92373]: fix gitops cluster linking api's (add agentIdentifier when mapping clusters to envs)

---

harness/policymgmt/model_update_request_body2.go

Due to presence of omitEmpty the policymgmt client was was setting the boolean field value to null instead of it's actual value to false. Removing this field let's the marshaller send the field as false
<details>

Fix : [CDS-93126]: Remove OmitEmpty

---

harness/nextgen/model_aws_sm_credential_spec_manual_config.go

Update TF support for AWS secret manager where now for access key can be added as either secret reference or plain text.
Change required:
Add support for new field accessKeyPlainText introduce in AWS SM.
<details>

feat: [PL-48648]: Update TF support for AWS secret manager accesskeyplaintext. 

---

harness/nextgen/api_service_overrides.go
harness/nextgen/docs/ServiceOverrideRequestDtov2.md
harness/nextgen/docs/ServiceOverridesResponseDtov2.md
harness/nextgen/model_service_override_import_request_dto.go
harness/nextgen/model_service_override_request_dtov2.go
harness/nextgen/model_service_overrides_response_dtov2.go

1. Earlier we were using GET API with path "get-with-yaml" for overrides v2 terraform resource. But with the new resource, we can use the simple GET API. So added that. 
2. Added support for identifier field in overrides v2 request and import request classes. This is to support optional identifier fields in new overrides v2 terraform resource. 
<details>

[feat]: [CDS-98538] Add new get api for overrides v2

---

harness/nextgen/api_agents.go
harness/nextgen/api_applications.go
harness/nextgen/api_clusters.go
harness/nextgen/api_gnu_pgp_keys.go
harness/nextgen/api_project_mappings.go
harness/nextgen/api_projects.go
harness/nextgen/api_repositories.go
harness/nextgen/api_repository_certificates.go
harness/nextgen/api_repository_credentials.go

Currently errors being returned when terraform fails are not very descriptive and make it hard to debug problem with terraform pipelines.
This should wrap error returned from API and prepare it for Harness terraform provider to be able to include it in diagnostics.
<details>

fix: [CDS-100484]: Improve error handling and errors returned to user for gitops

---

harness/nextgen/api_applications.go
harness/nextgen/api_clusters.go
harness/nextgen/api_repositories.go

When resoruce is deleted outside the terraform flow it should get recreted on terraform apply if resoruce is still in the terraform state file.
Additionally making account, org, project, agent and identifier for repository, cluster and application as immutable fields, as these are not possible to change after creation.
<details>

fix: [CDS-100484]: Improve error logging, recreate resource if exists in terraform state file.

---

harness/nextgen/api_applications.go
harness/nextgen/api_clusters.go
harness/nextgen/api_project_mappings.go
harness/nextgen/api_repositories.go

When resource is not found it should get recreated in terraform, this is fix for app project mapping,
need to cast response to proper error so that it can be handled by harness terraform provider
<details>

fix: [CDS-99032]:  Fix error handling for app project mapping

---

harness/nextgen/model_git_config.go

This field adds support for Git Connector to execute on Harness Platform Directly
Ran the test as well against this 
This change didn't get merged for this  https://github.com/harness/terraform-provider-harness/pull/1027
<details>

Add Support for Execute on Delegate in Git Connector

---

harness/nextgen/api_applications.go

When creating gitops app with multi sources we need to provide list of repo identifiers so that repos can be validated. list is sent in as get  query params.
<details>

fix: [CDS-98794]: Enable sending array of repo identifiers for multi source apps.

---

harness/nextgen/docs/AwsManualConfigSpec.md
harness/nextgen/model_aws_manual_config_spec.go

Added SessionTokenRef to AWS Manual Config. This parameter is optional, hence added omitempty.
<details>

fix: [CDS-102292]: Added SessionTokenRef to AWS Manual Config

---

harness/cd/unpublished/types.go
harness/nextgen/docs/AwsSecretManager.md
harness/nextgen/model_aws_secret_manager.go

This PR covers changes to give user ability to retrieve a deleted secret in AWS Secret Manager if accidentaly deleted from Harness. When configuring a AWS SM connector in Harness use can now choose between two additional fields:
Tested for:
- Created connector with recovery period of 15 days
- Error is thrown when recovery period is selected as 5 
- Created connector with ForceDeleteWithoutRecovery as true
-
<details>

feat: [PL-58650]: Terraform Changes for Add support for configuring recovery duration in AWS Secrets Manager Connector for secret deletion flow

---

harness/nextgen/model_opts.go
harness/nextgen/model_service_v2.go

Add Dry-run optional param to opts in service
API link: https://apidocs.harness.io/tag/Cloud-Cost-AutoStopping-Rules#operation/UpdateAutoStoppingRule
<details>

[feat]: [CCM-17096]: Add Dry-run option when creating the auto-stopping rules using terraform

---

harness/nextgen/api_agents.go
harness/nextgen/docs/AgentsApi.md

Most of the changes are generated by swagger-codegen. There are few changes done manually:
<details>

feat: [CDS-99979]: Update GitOps Agents API to add Agent Operator Yaml API

---

harness/dbops/api/swagger.yaml
harness/dbops/docs/DbInstanceIn.md
harness/dbops/docs/DbInstanceOut.md
harness/dbops/model_db_instance_in.go
harness/dbops/model_db_instance_out.go

Terraform: update instance for supporting overriding properties in changelogs
1. Can specify 1 or more properties to override
2. Can specify static names and values for those properties in the edit db instance UI
3. These overrides are passed to all liquibase commands.
JIRA -  https://harness.atlassian.net/browse/DBOPS-1073
<details>

[DBOPS-1073]: Update instance for overriding properties in changelogs

---

harness/nextgen/model_cluster_orchestrator.go

This PR aims to update Cluster Orch Config Model in Harness Go SDK, it exports sub-models of configs so that can be initialized and assigned in Terraform Provider Client. Also, it extends Replacement window option for Cluster Orch for Reverse Fallback and Consolidation
<details>

feat: [CCM-24158]: Updating Cluster Orch Config Model and Enhancing Replacement Window Applies to Options

---

harness/chaos/model_all_ofv1_toleration_effect.go
harness/chaos/model_all_ofv1_toleration_operator.go
harness/chaos/model_all_ofv1_volume_mount_mount_propagation.go

feat: [CHAOS-8832]: fix toleration and volume mount structure
This is required for chaos infra v2 support.
<details>
[CHAOS-8832]: https://harness.atlassian.net/browse/CHAOS-8832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [CHAOS-8832]: fix toleration and volume mount structure

---

harness/nextgen/model_artifactory_connector.go

The `ExecuteOnDelegate` option is missing from several types, like `ArtifactoryConnector`. This is to be used later in another PR in https://github.com/harness/terraform-provider-harness 
<details>
- Build Test: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`
- Git Leaks: `trigger gitleaks`
- Message Check: `trigger messagecheck`
</details>

feat: add missing ExecuteOnDelegate option for artifactory connector
